//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlaceWpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Useer Useer { get; set; }
    }
}
